from __future__ import annotations

import pandas as pd


def generate_long_only_trades(
    df: pd.DataFrame,
) -> tuple[pd.Series, pd.Series]:
    """
    Convert HalfTrend signals into long-only execution positions.

    Signals generated at the close of bar N are executed at the
    open of bar N+1, matching the default TradingView strategy
    execution behavior.

    Parameters
    ----------
    df:
        DataFrame containing open, close, buy_signal, and sell_signal.

    Returns
    -------
    positions:
        Position held during each bar. 1.0 for long, 0.0 for flat.

    trade_results:
        P&L in points for each completed long trade.
    """
    required = {
        "open",
        "close",
        "buy_signal",
        "sell_signal",
    }

    missing = required - set(df.columns)

    if missing:
        raise ValueError(
            f"Missing required columns: {sorted(missing)}"
        )

    n = len(df)

    positions = pd.Series(
        0.0,
        index=df.index,
        name="position",
    )

    trade_results: list[float] = []

    in_position = False
    entry_price: float | None = None

    for i in range(n):
        # --------------------------------------------------------------
        # Orders generated by the previous bar are executed at the
        # current bar's open.
        # --------------------------------------------------------------
        if i > 0:
            if df["buy_signal"].iloc[i - 1] and not in_position:
                entry_price = float(df["open"].iloc[i])
                in_position = True

            elif df["sell_signal"].iloc[i - 1] and in_position:
                exit_price = float(df["open"].iloc[i])

                trade_results.append(
                    exit_price - entry_price
                )

                entry_price = None
                in_position = False

        positions.iloc[i] = 1.0 if in_position else 0.0

    trade_results_series = pd.Series(
        trade_results,
        name="trade_results",
        dtype=float,
    )

    return positions, trade_results_series